apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: process
spec:
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: blackopsrepl/work-queue-processor:latest
        imagePullPolicy: Always
        name: my-job
        env:
          - name: WORK_QUEUE_HOST
            value: "work-queue"
          - name: WORK_QUEUE_PORT
            value: "5672"
          - name: JOB_USER
            valueFrom:
              secretKeyRef:
                name: aws-credential-secret
                key: JOB_USER
          - name: JOB_PASS
            valueFrom:
              secretKeyRef:
                name: aws-credential-secret
                key: JOB_PASS
      restartPolicy: Never
status: {}
